stages:
  # Make the training file
  make_training_file:
    cmd: python3 makeTrainingFile.py
    deps:
      - makeTrainingFile.py
      - src/utils.py
      - src/trainingFiles.py
    params:
      - files
      - goodRuns
      - limitInputs
    outs:
      - data/dataFiles_output.h5
      - data/suepFiles_output.h5
      - data/VBFHToTauTauFiles_output.h5
      - data/TTFiles_output.h5

  # Make autoencoders

  make_cicada_teacher:
    cmd: python3 trainCICADA2026Teacher.py
    deps:
      - trainCICADA2026Teacher.py
      - data/dataFiles_output.h5
    params:
      - alpha
      - beta
      - inputFiles.dataFile
    outs:
      - data/teacher_model.keras
      - data/teacher_model_training_log.csv

  make_cicada_teacher_3Channel:
    cmd: "python3 trainCICADA2026Teacher.py --use3Channels"
    deps:
      - trainCICADA2026Teacher.py
      - data/dataFiles_output.h5
    params:
      - alpha
      - beta
      - inputFiles.dataFile
    outs:
      - data/teacher_model_3channel.keras
      - data/teacher_model_3channel_training_log.csv

  make_cicada_vae:
    cmd: python3 trainCICADA2026Teacher_VAE.py
    deps:
      - trainCICADA2026Teacher_VAE.py
      - data/dataFiles_output.h5
    params:
      - cicadaTeacherVAE3Channel
    outs:
      - data/teacher_model_vae.keras

  # Make any students or reduced models

  make_classic_student:
    cmd: python3 trainCICADAStudent_classic.py
    deps:
      - src/cicadaStudent_classic.py
      - trainCICADAStudent_classic.py
      - src/trainTeacher.py
      - data/teacher_model.keras
    params:
      - cicadaStudentClassic
      - cicadaStudentCommon
    outs:
      - data/cicadaStudent_classic
      - data/logs/classic_student_log.csv
      - data/classicScoreHisto.h5

  # make_3channel_vae_student:
  #   cmd: python3 trainCICADAStudent_vae_3channel.py
  #   deps:
  #     - src/cicadaStudent_vae_3channel.py
  #     - src/cicadaStudent_classic.py
  #     - trainCICADAStudent_vae_3channel.py
  #   params:
  #     - cicadaStudentVAE3Channel
  #     - cicadaStudentCommon
  #   outs:
  #     - data/3channel_vae_student
  #     - data/logs/3channel_vae_student_log.csv
  #     - data/3channelScoreHisto.h5

  make_encoder_only_model:
    cmd: python3 createEncoderOnlyModel.py
    deps:
      - src/teacher_vae
      - src/encoderOnlyModel.py
    params:
      - cicadaTeacherVAE3Channel
      - cicadaEncoderOnly
    outs:
      - data/encoderOnlyModel

  # Make any firmware.

  # Make evaluations

  # evaluate_classic_student:
  #   cmd: python3 studentEvaluation_classic.py
  #   deps:
  #     - src/evaluateStudent_classic.py
  #     - src/utils.py
  #     - src/cicadaStudent_classic.py
  #     - studentEvaluation_classic.py
  #     - data/cicadaStudent_classic
  #   params:
  #     - cicadaStudentClassic

  # evaluate_vae_student:
  #   cmd: python3 studentEvaluation_3channel_vae.py
  #   deps:
  #     - src/cicadaStudent_classic.py
  #     - src/cicadaStudent_vae_3channel.py
  #     - src/utils.py
  #     - studentEvaluation_3channel_vae.py
  #     - data/3channel_vae_student
  #   params:
  #     - cicadaStudentVAE3Channel
