stages:
  # Make the training file
  make_training_file:
    cmd: python3 makeTrainingFile.py
    deps:
      - makeTrainingFile.py
      - src/utils.py
      - src/trainingFiles.py
    params:
      - files
      - goodRuns
      - limitInputs
    outs:
      - data/dataFiles_training_output.h5
      - data/dataFiles_studentTraining_output.h5
      - data/dataFiles_output.h5
      - data/suepFiles_output.h5
      - data/VBFHToTauTauFiles_output.h5
      - data/TTFiles_output.h5

  # Make autoencoders

  make_cicada_teacher:
    cmd: python3 trainCICADA2026Teacher.py
    deps:
      - trainCICADA2026Teacher.py
      - data/dataFiles_training_output.h5
      - src/trainTeacher.py
    params:
      - alpha
      - beta
      - inputFiles.dataFile
    outs:
      - data/teacher_model.keras
      - data/teacher_model_training_log.csv

  make_cicada_teacher_3Channel:
    cmd: "python3 trainCICADA2026Teacher.py --use3Channels"
    deps:
      - trainCICADA2026Teacher.py
      - data/dataFiles_training_output.h5
    params:
      - alpha
      - beta
      - inputFiles.dataFile
    outs:
      - data/teacher_model_3channel.keras
      - data/teacher_model_3channel_training_log.csv

  make_cicada_vae:
    cmd: python3 trainCICADA2026Teacher_VAE.py
    deps:
      - trainCICADA2026Teacher_VAE.py
      - data/dataFiles_training_output.h5
      - src/teacher_vae.py
    params:
      - cicadaTeacherVAE3Channel
      - alpha
      - beta
    outs:
      - data/teacher_model_vae.keras
      - data/teacher_model_vae_log.csv

  make_cicada_3channel_vae:
    cmd: "python3 trainCICADA2026Teacher_VAE.py --use3Channels"
    deps:
      - trainCICADA2026Teacher_VAE.py
      - data/dataFiles_training_output.h5
      - src/teacher_vae.py
    params:
      - cicadaTeacherVAE3Channel
      - alpha
      - beta
    outs:
      - data/teacher_model_3channel_vae.keras
      - data/teacher_model_3channel_vae_log.csv

  # Make any students or reduced models

  make_classic_student:
    cmd: python3 trainCICADAStudent_classic.py
    deps:
      - src/cicadaStudent_classic.py
      - trainCICADAStudent_classic.py
      - src/trainTeacher.py
      - data/teacher_model.keras
      - data/dataFiles_studentTraining_output.h5
    params:
      - cicadaStudentClassic
      - cicadaStudentCommon
    outs:
      - data/cicadaStudent_classic.keras
      - data/logs/cicadaStudent_classic_log.csv
      - data/classicScoreHisto.h5

  make_classic_student_3channel:
    cmd: "python3 trainCICADAStudent_classic.py --use3Channels"
    deps:
      - src/cicadaStudent_classic.py
      - trainCICADAStudent_classic.py
      - src/trainTeacher.py
      - data/teacher_model_3channel.keras
      - data/dataFiles_studentTraining_output.h5
    params:
      - cicadaStudentClassic_3Channel
      - cicadaStudentCommon
    outs:
      - data/cicadaStudent_classic_3channel.keras
      - data/logs/cicadaStudent_classic_3channel_log.csv
      - data/classic3ChannelScoreHisto.h5

  # make_3channel_vae_student:
  #   cmd: python3 trainCICADAStudent_vae_3channel.py
  #   deps:
  #     - src/cicadaStudent_vae_3channel.py
  #     - src/cicadaStudent_classic.py
  #     - trainCICADAStudent_vae_3channel.py
  #   params:
  #     - cicadaStudentVAE3Channel
  #     - cicadaStudentCommon
  #   outs:
  #     - data/3channel_vae_student
  #     - data/logs/3channel_vae_student_log.csv
  #     - data/3channelScoreHisto.h5

  make_encoder_only_model:
    cmd: python3 createEncoderOnlyModel.py
    deps:
      - createEncoderOnlyModel.py
      - src/teacher_vae.py
      - src/encoderOnlyModel.py
    params:
      - cicadaTeacherVAE3Channel
      - cicadaEncoderOnly
    outs:
      - data/encoderOnlyModel.keras
      - data/encoderOnlyModel_pythonUsability.keras

  # Make any firmware.
  # Encoder only
  make_encoder_firmware:
    cmd: python3 makeEncoderFirmware.py
    params:
      - cicadaEncoderOnly
    deps:
      - data/encoderOnlyModel.keras
      - data/encoderOnlyModel_pythonUsability.keras
      - makeEncoderFirmware.py

  # Make evaluations

  # evaluate_classic_student:
  #   cmd: python3 studentEvaluation_classic.py
  #   deps:
  #     - src/evaluateStudent_classic.py
  #     - src/utils.py
  #     - src/cicadaStudent_classic.py
  #     - studentEvaluation_classic.py
  #     - data/cicadaStudent_classic
  #   params:
  #     - cicadaStudentClassic

  # evaluate_vae_student:
  #   cmd: python3 studentEvaluation_3channel_vae.py
  #   deps:
  #     - src/cicadaStudent_classic.py
  #     - src/cicadaStudent_vae_3channel.py
  #     - src/utils.py
  #     - studentEvaluation_3channel_vae.py
  #     - data/3channel_vae_student
  #   params:
  #     - cicadaStudentVAE3Channel

  # test firmware latency
  copy_firmware:
    cmd: "python3 copyScript.py encoder_only_firmware/firmware ctp7cpp/vivado_hls/src/"
    deps:
      - copyScript.py
      - data/encoderOnlyModel.keras

  #TODO: Add synthesis testing?
