files:
  dataFiles: /hdfs/store/user/aloeliger/CICADATraining2026/ZeroBias_Operations_Run2025G
  suepFiles: /hdfs/store/user/aloelige/SUEP/AnomalyDetectionPaper2025_SUEP_User_03Jul2025
  VBFHToTauTauFiles: /hdfs/store/user/aloelige/VBFHToTauTau_M125_TuneCP5_13p6TeV_powheg-pythia8/AnomalyDetectionPaper2025_VBFHToTauTau_Winter24_05May2025
  TTFiles: /hdfs/store/user/aloelige/TT_TuneCP5_13p6TeV_powheg-pythia8/AnomalyDetectionPaper2025_TT_Winter24_01May2025

inputFiles:
  dataFile: data/dataFiles_output.h5
  suepFile: data/suepFiles_output.h5
  VBFFile: data/VBFHToTauTauFiles_output.h5
  TTFile: data/TTFiles_output.h5

score_name: CICADA2025_CICADAScore

goodRuns:
- 398027
- 398040
- 398081
- 398104
- 398144
- 398183
- 398188
- 398189
- 398203
- 398204
- 398208
- 398227
- 398240
- 398288
- 398293
- 398308
- 398310
- 398315
- 398335
- 398337
- 398348
- 398365
- 398368
- 398391
- 398395
- 398396
- 398149
- 398458
- 398459
- 398515
- 398517
- 398539
- 398540
- 398541
- 398547
- 398548
- 398549
- 398558
- 398593
- 398600
- 398647
- 398648
- 398650
- 398680
- 398802
- 398827
- 398828
- 398860

limitInputs: 100000

alpha: 1.0
beta: 1.0

cicadaTeacherVAE3Channel:
  latentSpaceSize: 32

cicadaStudentCommon:
  dataFileDilation: 15
  fileDir: /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/
  singleWDir: /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/singleW/h5/singleW_withPUinfo_files/

cicadaStudentClassic:
  teacherModel: data/teacher_model.keras
  scoreHistogramOutput: data/classicScoreHisto.h5
  ROCPlot: data/classicStudent_ROCPlot.png

cicadaStudentClassic_3Channel:
  teacherModel: data/teacher_model_3channel.keras
  scoreHistogramOutput: data/classic3ChannelScoreHisto.h5
  ROCPlot: data/classicStudent3Channel_ROCPlot.png

cicadaStudentVAE3Channel:
  teacherModel: data/three_channel_teacher/
  scoreHistogramOutput: data/3channelScoreHisto.h5
  ROCPlot: data/VAEStudent_ROCPlot.png

cicadaEncoderOnly:
  model: data/teacher_model_vae.keras
  # layers: [
  # # "teacher_inputs_",
  # # "teacher_reshape",
  # # "slice_energy",
  # # "log1p_energy",
  # # "slice_binary",
  # # "merge_inputs",
  # "enc_conv_1",
  # "enc_relu_1",
  # "enc_pool_1",
  # "enc_conv_2",
  # "enc_relu_2",
  # "enc_flatten",
  # "z_mean",
  # ]
  layers: [
  "normLayer",
  "conv_1",
  "conv_1_act",
  "maxPool",
  #"denoise",
  "conv_2",
  "conv_2_act",
  "flat",
  "dropout",
  "z_mu",
  ]
  pythonUsabilityLayers: [
  "teacher_inputs_",
  "teacher_reshape",
  "slice_energy",
  "log1p_energy",
  "slice_binary",
  "merge_inputs",
  "enc_conv_1",
  "enc_relu_1",
  "enc_pool_1",
  "enc_conv_2",
  "enc_relu_2",
  "enc_flatten",
  "z_mean",
  ]
  outputModel: data/encoderOnlyModel
