files:
  dataFiles: /hdfs/store/user/aloeliger/CICADATraining2026/ZeroBias_Operations_Run2025G
  suepFiles: /hdfs/store/user/aloelige/SUEP/AnomalyDetectionPaper2025_SUEP_User_03Jul2025
  VBFHToTauTauFiles: /hdfs/store/user/aloelige/VBFHToTauTau_M125_TuneCP5_13p6TeV_powheg-pythia8/AnomalyDetectionPaper2025_VBFHToTauTau_Winter24_05May2025
  TTFiles: /hdfs/store/user/aloelige/TT_TuneCP5_13p6TeV_powheg-pythia8/AnomalyDetectionPaper2025_TT_Winter24_01May2025

score_name: CICADA2025_CICADAScore

goodRuns:
- 398027
- 398040
- 398081
- 398104
- 398144
- 398183
- 398188
- 398189
- 398203
- 398204
- 398208
- 398227
- 398240
- 398288
- 398293
- 398308
- 398310
- 398315
- 398335
- 398337
- 398348
- 398365
- 398368
- 398391
- 398395
- 398396
- 398149
- 398458
- 398459
- 398515
- 398517
- 398539
- 398540
- 398541
- 398547
- 398548
- 398549
- 398558
- 398593
- 398600
- 398647
- 398648
- 398650
- 398680
- 398802
- 398827
- 398828
- 398860

limitInputs: 10000000

alpha: 1.0
beta: 1.0
cicadaStudentCommon:
  fileList: [
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d0fbdc0-5893-41f7-8237-6343f33ad485.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d13496d-71bd-4c37-a201-423d643fbc7b.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d2de03c-75ad-42a4-8c11-36d304aa812d.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d3e78a2-c0db-46fd-b02c-e5270de7700a.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d461d27-1b89-403c-86bd-cd0f049c6bab.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d4d668d-b072-4507-a81c-8b424aada72a.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d4f6841-9bd8-4634-8657-0eae67458b91.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d60fd6b-91b2-435e-a47a-698d66bb6eee.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d658981-510a-4715-8aff-2e237c7e229d.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d68ed3f-ff91-47ce-9af3-6ae65a474725.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d7d6cd1-5ea6-4f88-8686-78aab824ff6b.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d827543-5bee-4409-84db-0ba99b5f4bf9.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d8c5999-71c4-47ac-abba-83c4e84612df.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d8d5727-c177-4e3f-b104-9fac58c95e53.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d95af9b-85df-4d8a-a256-d6253bd61737.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5d9ff30e-5861-4dbc-8d49-e7f690d287d7.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5daba59c-06d5-4b38-b5a9-db861b6e8cc9.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5daf1b53-5caa-4941-8de1-72159bd516ca.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5db98625-0364-46e4-89ae-501ffb58757d.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5dbdf6c7-5592-4fae-ae99-cd5e66633481.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ddd2f1f-5550-44f9-8aa2-d78cf2875647.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5dddbe3c-792d-43d5-b417-88b3bf18f013.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ddff19d-4fb9-49d5-9775-c4549cb0eb48.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5de5e55b-8bf3-4389-aeab-cb93104768d2.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5dfbc43a-5fba-4f36-a296-04cfccae8604.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e090022-747f-4c75-bcb8-c07641833880.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e09dc11-d5b8-45a8-b9ee-d15cdf641f7d.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e0c01ad-f26c-4327-9de7-af62c12800e1.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e20ab79-44e9-4581-8b51-3b4bf4cac7cf.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e33f464-1bfc-4e94-8698-f853bb01730c.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e3c33e0-df4d-4560-9c63-c9331ef3278f.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e3e7d18-584d-4d81-8519-707a46de6292.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e40cdbe-1d75-4c13-92b9-71538342833f.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e43f154-8602-4211-9415-1467374ff72c.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e68ad8f-f103-45ed-90dd-68d63c6d9eb5.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e699c5d-fcb4-4880-9c91-b4b9fadace8f.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e6f4a5c-731b-4c7f-978e-90d7236990d4.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e85d8b0-49cf-40ed-a44a-64d9aa6830c6.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e877531-baab-403d-b33d-2a491d4b3b24.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e9920a1-67f5-4dd7-84f6-0178b004e0fb.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5e996768-c887-4e53-b22e-a19a7c675cfd.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ea0e82f-dfd8-4e23-b827-7aeb87290b68.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5eab5ed4-f0f8-4592-ad36-09fa89882c5d.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ec368d8-db1d-46e9-883d-1de5396be99e.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ecace9e-1ffd-4f94-9a97-2997b88e057d.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ecb03f5-dc1a-4306-8eb3-bcc4db41975b.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ed609ef-42b3-497e-9db8-4284e1d2425a.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5edd8d4a-54dc-4ef9-b39b-c23c869fcfda.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ee783d4-51d8-4752-b693-3b3521b6dd43.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5eedfc36-e97a-4b98-a13f-aab2907949e5.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5eefc9dd-d57b-4cbe-8910-145581a99767.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ef84aff-1db6-4070-bae4-d2a271a25d88.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5efa04a3-576f-415c-bba1-d119f7365eef.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f054d92-9d32-4c09-be20-295a2b076200.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f06fefa-7ce0-4cb9-b283-45a0aaebb0a8.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f0b3f17-e837-4b29-b4f8-9236c18785c7.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f25fae4-27c3-47ef-94bc-b587b1b96330.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f2e04aa-4a8b-476a-8f6f-88b6e17455ee.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f3276e3-7fcf-45c3-b025-055252f4a4a3.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f3db53c-f774-4dc0-adf0-409e25094ae5.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f3e6652-fc9f-48e2-8f8d-95e510f79588.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f41996b-18b7-4b7a-9687-2a1608501067.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f48c69e-9e16-45a5-83e6-df7099d86695.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f528654-7413-43d2-a1c6-ade89fc01442.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f543708-44e0-478c-b84a-7e5076d6da08.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f57e7a7-99fe-4d9c-974b-8a5d88b583fe.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f595417-3a91-4b22-81f5-b731a7a218ef.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f5d89f3-0c5a-4907-8f53-8c869e0df4be.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f66e2af-e211-40cd-b748-ef59602f71dd.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f6e1c4f-d86a-45ef-8419-1695fb6bd0e9.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f6f129e-8bf9-411c-978c-144933263102.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f73358d-00e9-42d0-99a6-63e003a127b7.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f74da0c-1253-4bad-9251-0a226482ff93.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f7c350b-f73e-4c63-a680-b73c975db397.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f869d71-2e16-4bc8-b4b0-2e9f933cd406.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f890723-9bc9-4fa3-bdc5-713d8afc3439.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f8a43a1-ca16-4dd5-8dc8-6b83124e1299.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f9138c0-ad0a-41f6-837f-707b4ac8d89a.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5f9bbf38-4f31-48de-97fc-1d958e74bfe4.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fb25677-4b05-4ea8-850d-66a2aac90d4a.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fbe3043-a507-44ce-a434-36fcdcc15458.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fbfc81e-0829-4d57-ba9d-a6af795a2383.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fc5a836-fafa-4a4b-81e5-a8664325b8c5.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fcb3a6d-e4d3-4d11-821e-813c6a54b0cb.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fd37f2b-c003-4a80-bb41-f38610aaffe4.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fd46c7f-6729-4a61-8c11-0f0fe8473460.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fd67d3d-81c4-4563-8708-55a1dffc10a6.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fdbae2f-999a-467c-8891-2ee4dcd0e980.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fe4e7a6-4d62-4f67-9ed2-de3be7d68e28.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5fe59eb4-8fa0-4324-900a-dd71ae852fa2.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ff45e9f-5a1a-4e30-8cb6-b7e53a5634fe.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-5ffed69b-a44e-443a-b1d7-b5c8dd8a9e25.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-6006b5d1-9ba0-4235-92e5-8c09ac5468fd.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-600d5756-0630-458d-adaf-ef3441cf7f8b.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-6018928c-b1f7-46e6-9960-ed2f565d3b92.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-60257a96-38d7-45df-982f-028548ab4e52.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-602980f2-88ff-4528-b2e4-9b66e3e00fbe.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-602cc105-2ac5-47a9-800c-3b23d2f2d8df.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-602fd288-c57b-4ee0-bb04-08e9ba97bf7b.h5,
  /hdfs/store/user/mallampalli/internal_cicada_files/withPUinfo/ZB/h5/ZB_withPUinfo_files/l1nano_AD-b46549d1-f286-45af-ad24-16d2faad4b3c.h5,
  ]
cicadaStudentClassic:
  teacherModel: data/only_energy_teacher
cicadaStudentVAE3Channel:
  teacherModel: data/three_channel_teacher/
